Added emailer and got ntp to work, motor still hasn't arrived in the mail yet...gonna go play grounded

diff --git a/custom_init.d_files/S45ntpd b/custom_init.d_files/S45ntpd
--- a/custom_init.d_files/S45ntpd
+++ b/custom_init.d_files/S45ntpd
@@ -1,43 +1,34 @@
-#!/bin/sh
-#
-# Start ntpd
-#
+#! /bin/sh
 
-server=pool.ntp.org
+NAME=ntpd
 
-TZ=${timezone:-America/Chicago}
-export TZ
-[ -e /etc/TZ ] && rm /etc/TZ
-ln -s /usr/share/zoneinfo/uclibc/$TZ /etc/TZ
-
-start() {
-	echo -n "Starting ntpd: "
-	ntpd -p $server
-	pidof ntpd > /var/run/ntpd.pid
-	echo "OK"
-}
-
-stop() {
-	echo -n "Stopping ntpd: "
-	kill -TERM `cat /var/run/ntpd.pid`
-	echo "OK"
-}
+# Read config file if it is present.
+if [ -r /etc/default/$NAME ]
+then
+  . /etc/default/$NAME
+fi
 
 case "$1" in
-	start)
-		start
-		;;
-	stop)
-		stop
-		;;
-	restart|reload)
-		stop
-		start
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart}"
-		exit 1
+  start)
+    printf "Starting $NAME: "
+    start-stop-daemon -S -q -x /usr/sbin/ntpd -- -g
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
+  stop)
+    printf "Stopping $NAME: "
+    start-stop-daemon -K -q -n $NAME
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    ;;
+  restart|reload)
+    echo "Restarting $NAME: "
+    $0 stop
+    sleep 1
+    $0 start
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|reload}" >&2
+    exit 1
+    ;;
 esac
 
-exit $?
-
+exit 0
